name: Feature Extraction Workflow

on:
  schedule:
    # Runs every hour at the top of the hour
    - cron: '0 * * * *'
  workflow_dispatch:  # This allows to trigger manually as well

jobs:
  feature_extraction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter  # Install Jupyter to run notebooks

    - name: Run Jupyter notebook for feature extraction
      run: |
        jupyter nbconvert --execute --inplace --to notebook Arbaz_Aslam_AQI_Project.ipynb  # Run the feature extraction part of the notebook
