name: Streamlit App CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - app.py
      - requirements.txt
      - "*.pkl"
      - .github/workflows/streamlit_app.yml

jobs:
  run-app-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit app (test mode)
        run: |
          streamlit run app.py --server.headless true &
          sleep 10
